version: "3"

services:
 serverapp:
  build:
   context: "./server"
   dockerfile: "Dockerfile"
  networks:
   - conf_net
  ports:
   - "127.0.0.1:8081:8081"

 clientapp:
  build:
   context: "./client"
   dockerfile: "Dockerfile"
  networks:
     - conf_net
  depends_on:
  - serverapp

networks:
  conf_net:
   driver: bridge

