version: "3"

services:
 serverapp:
  build:
   context: "."
   dockerfile: "Dockerfile"
  networks:
   - conf_net
  ports:
   - "127.0.0.1:3000:3000"
  depends_on:
   - db


# clientapp:
#  build:
#   context: "."
#   dockerfile: "client/client.Dockerfile"
#  networks:
#   - conf_net
#  depends_on:
#   - serverapp
#   - db

 clientapp:
  build:
   context: "."
   dockerfile: "restClient.Dockerfile"
  networks:
   - conf_net
  ports:
   - "127.0.0.1:8080:8080"
  depends_on:
   - serverapp
   - db

 db:
  image: postgres
  restart: always
  networks:
   - conf_net
#  environment:
#   - POSTGRES_USER=postgres
#   - POSTGRES_PASSWORD=root
  volumes:
    - /tmp/pgdata:/var/lib/postgresql/data

networks:
  conf_net:
   driver: bridge


