version: "3"

services:
 serverapp:
  env_file: .env
  build:
   context: "."
   dockerfile: "Dockerfile"
  networks:
   - conf_net
  ports:
   - "127.0.0.1:${SERVICE_PORT}:${SERVICE_PORT}"
  depends_on:
   - db

 db:
  image: postgres
  restart: always
  networks:
   - conf_net
  volumes:
    - /tmp/pgdata:/var/lib/postgresql/data

networks:
  conf_net:
   driver: bridge


