
[metadata.heroku]
  root-package = "github.com/YAWAL/GetMeConf"
  go-version = "1.9.4"
  install = [ "./..." ]
  
[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/alecthomas/gometalinter"
version = "2.0.5"